version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: data-compliance-service
    AWS_ACCOUNT_ID: 533333767769

phases:
  install:
    runtime-versions:
      docker: 19
      python: 3.8
    commands:
      - pip install poetry taskipy
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - task test
