version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: data-compliance-service
    AWS_ACCOUNT_ID: 533333767769

phases:
  install:
    runtime-versions:
      docker: 19
      python: 3.8
    commands:
      - pip install poetry taskipy
  build:
    commands:
      - task test
