version: "2.4"

services:
  vigilantkeeper:
    image: vigilantkeeper
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace
    runtime: $DOCKER_RUNTIME
    volumes:
      - .:/workspace
    depends_on:
      postgres-db:
        condition: service_healthy
  postgres-db:
    image: 533333767769.dkr.ecr.us-gov-west-1.amazonaws.com/postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "local_db", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
