# coding: utf-8
from sqlalchemy import (
    BigInteger,
    Column,
    Date,
    DateTime,
    Integer,
    Numeric,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class GdmsQuestionnaire(Base):
    __tablename__ = "gdms_questionnaire"
    __table_args__ = {"schema": "audit"}

    question_id = Column(Integer, primary_key=True)
    question_text = Column(String(5000), nullable=False)
    timeline = Column(String(255), nullable=False)


class VkAlpha(Base):
    __tablename__ = "vk_alpha"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    network = Column(String(255), nullable=False)
    domain = Column(String(255), nullable=False)
    displayname = Column(String(255), nullable=False)
    cn = Column(String(255), nullable=False)
    givenname = Column(String(255), nullable=False)
    sn = Column(String(255), nullable=False)
    userid = Column(String(255), nullable=False)
    telephonenumber_int = Column(String(255), nullable=False)
    mail = Column(String(255), nullable=False)
    department = Column(String(255), nullable=False)
    company = Column(String(255), nullable=False)
    location = Column(String(255), nullable=False)
    member = Column(String(255), nullable=False)
    ou = Column(String(255), nullable=False)
    manager = Column(String(255), nullable=False)
    distinguishedname = Column(String(255), nullable=False)


class VkDelta(Base):
    __tablename__ = "vk_delta"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    dia_facility_access_index = Column(Integer, nullable=False)
    dia_person_key = Column(String, nullable=False)
    event_date = Column(String, nullable=False)
    first_name = Column(String, nullable=False)
    middle_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    suffix_name = Column(String, nullable=False)
    ssn = Column(String, nullable=False)
    badge_number = Column(String, nullable=False)
    facility = Column(String, nullable=False)
    date_format = Column(String, nullable=False)
    location_desc = Column(String, nullable=False)
    location_code = Column(String, nullable=False)
    badge_sponsor = Column(String, nullable=False)
    data_src = Column(String, nullable=False)
    uuid = Column(String, nullable=False)
    ssn_int = Column(Integer, nullable=False)


class VkEcho1of3(Base):
    __tablename__ = "vk_echo_1of3"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    emp_id = Column(BigInteger, nullable=False)
    emp_rec_num = Column(Integer, nullable=False)
    emp_nm_pre = Column(String(255), nullable=False)
    emp_name = Column(String(255), nullable=False)
    cur_emp_dir = Column(String(255), nullable=False)
    emp_subelement = Column(String(255), nullable=False)
    cur_emp_deptid = Column(String(255), nullable=False)
    emp_bnd_grd = Column(Integer, nullable=False)
    emp_jobcode = Column(String(255), nullable=False)
    emp_active_ind = Column(String(255), nullable=False)
    emp_civ_mil = Column(String(255), nullable=False)
    cur_emp_pp = Column(String(255), nullable=False)
    person_type = Column(String(255), nullable=False)
    person_type2 = Column(String(255), nullable=False)
    rpt_dt = Column(Date, nullable=False)
    time_reporting_code = Column(String(255), nullable=False)
    quantity = Column(Numeric, nullable=False)
    user = Column(String(255), nullable=False)
    approved_at = Column(String(255), nullable=False)
    status = Column(String(255), nullable=False)


class VkEcho2of3(Base):
    __tablename__ = "vk_echo_2of3"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    emp_id = Column(String, nullable=False)
    emp_rec_num = Column(Integer, nullable=False)
    indicatior = Column(String, nullable=False)
    emp_name = Column(String, nullable=False)
    emp_active_ind = Column(String, nullable=False)
    emp_civ_mil = Column(String, nullable=False)
    person_type = Column(String, nullable=False)
    person_type_descr = Column(String, nullable=False)
    emp_subelement = Column(String, nullable=False)
    cur_emp_deptid = Column(String, nullable=False)
    emp_ssn = Column(String, nullable=False)
    emp_userid = Column(String, nullable=False)
    emp_sci_email = Column(String, nullable=False)
    emp_age_group = Column(String, nullable=False)
    emp_b_day = Column(String, nullable=False)
    emp_b_month = Column(String, nullable=False)
    emp_citizenship = Column(String, nullable=False)
    emp_flpp_lang_1 = Column(String, nullable=False)
    emp_flpp_lvl_1 = Column(String, nullable=False)
    emp_1st_hire_dt = Column(String, nullable=False)
    emp_last_hiredt = Column(String, nullable=False)
    emp_tenure = Column(String, nullable=False)
    dia_years = Column(Integer, nullable=False)
    dia_yrs_brkout = Column(String, nullable=False)
    emp_term_dt = Column(String, nullable=False)
    emp_nte_dt = Column(String, nullable=False)
    emp_bnd_grd = Column(String, nullable=False)
    emp_bnd_grd_dt = Column(String, nullable=False)
    emp_time_gr_bnd = Column(String, nullable=False)
    emp_jobcode = Column(String, nullable=False)
    emp_category = Column(String, nullable=False)
    emp_level = Column(String, nullable=False)
    emp_occ_group = Column(String, nullable=False)
    emp_occ_spec = Column(String, nullable=False)
    emp_mgr_lvl = Column(String, nullable=False)
    cur_emp_loc = Column(String, nullable=False)
    emp_loc_name = Column(String, nullable=False)
    emp_loc_conus = Column(String, nullable=False)
    emp_loc_geo_cd = Column(String, nullable=False)
    cur_emp_title = Column(String, nullable=False)
    emp_ext_org = Column(String, nullable=False)
    cur_emp_series = Column(String, nullable=False)
    emp_std_hours = Column(Integer, nullable=False)
    emp_total_pay = Column(Integer, nullable=False)
    emp_from_agency = Column(String, nullable=False)
    emp_to_agency = Column(String, nullable=False)
    emp_govt_yrs = Column(Integer, nullable=False)
    govt_yrs_brkout = Column(String, nullable=False)
    emp_work_sched = Column(String, nullable=False)
    emp_1st_bus_ph = Column(String, nullable=False)
    emp_2st_bus_ph = Column(String, nullable=False)
    emp_1st_cell_ph = Column(String, nullable=False)
    emp_persnl_cell = Column(String, nullable=False)
    emp_1st_dsn_ph = Column(String, nullable=False)
    emp_unsec_fax = Column(String, nullable=False)
    emp_sec_fax = Column(String, nullable=False)
    emp_home_ph = Column(String, nullable=False)
    emp_1st_pager = Column(String, nullable=False)
    emp_2nd_pager = Column(String, nullable=False)
    emp_1st_sec_ph = Column(String, nullable=False)
    emp_2nd_sec_ph = Column(String, nullable=False)
    emp_dvtc_ph = Column(String, nullable=False)
    emp_voip_ph = Column(String, nullable=False)
    emp_room_nbr = Column(String, nullable=False)
    emp_hm_addr_1_4 = Column(String, nullable=False)
    emp_hm_city = Column(String, nullable=False)
    emp_hm_state = Column(String, nullable=False)
    emp_hm_zip = Column(String, nullable=False)
    emp_ed_hi_lvl = Column(String, nullable=False)
    emp_ed_hideg = Column(String, nullable=False)
    emp_ed_himajor = Column(String, nullable=False)
    emp_vet_pref = Column(String, nullable=False)
    emp_mil_service = Column(String, nullable=False)
    emp_mil_cat = Column(String, nullable=False)
    cor_name = Column(String, nullable=False)
    onsite_loc = Column(String, nullable=False)
    offsite_loc = Column(String, nullable=False)
    hrs_on_contract = Column(Integer, nullable=False)
    emp_loc_ncr = Column(String, nullable=False)
    emp_gender = Column(String, nullable=False)


class VkEcho3of3(Base):
    __tablename__ = "vk_echo_3of3"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    emp_id = Column(String, nullable=False)
    emp_rec_num = Column(Integer, nullable=False)
    indicator = Column(String, nullable=False)
    emp_name = Column(String, nullable=False)
    emp_active_ind = Column(String, nullable=False)
    emp_civ_mil = Column(String, nullable=False)
    person_type = Column(String, nullable=False)
    person_type_descr = Column(String, nullable=False)
    emp_subelement = Column(String, nullable=False)
    cur_emp_deptid = Column(String, nullable=False)
    emp_ssn = Column(String, nullable=False)
    emp_userid = Column(String, nullable=False)
    emp_sci_email = Column(String, nullable=False)
    emp_age_group = Column(String, nullable=False)
    emp_b_day = Column(String, nullable=False)
    emp_b_month = Column(String, nullable=False)
    emp_citizenship = Column(String, nullable=False)
    emp_flpp_lang_1 = Column(String, nullable=False)
    emp_flpp_lvl_1 = Column(String, nullable=False)
    emp_1st_hire_dt = Column(String, nullable=False)
    emp_last_hire_dt = Column(String, nullable=False)
    emp_tenure = Column(String, nullable=False)
    dia_years = Column(Integer, nullable=False)
    dia_yrs_brkout = Column(String, nullable=False)
    emp_term_dt = Column(String, nullable=False)
    emp_nte_dt = Column(String, nullable=False)
    emp_bnd_grd = Column(String, nullable=False)
    emp_bnd_grd_dt = Column(String, nullable=False)
    emp_time_gr_bnd = Column(String, nullable=False)
    emp_jobcode = Column(String, nullable=False)
    emp_category = Column(String, nullable=False)
    emp_level = Column(String, nullable=False)
    emp_occ_group = Column(String, nullable=False)
    emp_occ_spec = Column(String, nullable=False)
    emp_mgr_lvl = Column(String, nullable=False)
    cur_emp_loc = Column(String, nullable=False)
    emp_loc_name = Column(String, nullable=False)
    emp_loc_conus = Column(String, nullable=False)
    emp_loc_geo_cd = Column(String, nullable=False)
    cur_emp_title = Column(String, nullable=False)
    emp_ext_org = Column(String, nullable=False)
    cur_emp_series = Column(String, nullable=False)
    emp_std_hours = Column(Integer, nullable=False)
    emp_total_pay = Column(Integer, nullable=False)
    emp_from_agency = Column(String, nullable=False)
    emp_to_agency = Column(String, nullable=False)
    emp_govt_yrs = Column(Integer, nullable=False)
    govt_yrs_brkout = Column(String, nullable=False)
    emp_wrk_sched = Column(String, nullable=False)
    emp_1st_bus_ph = Column(String, nullable=False)
    emp_2nd_bus_ph = Column(String, nullable=False)
    emp_1st_cell_ph = Column(String, nullable=False)
    emp_persnl_cell = Column(String, nullable=False)
    emp_1st_dsn_ph = Column(String, nullable=False)
    emp_unsec_fax = Column(String, nullable=False)
    emp_sec_fax = Column(String, nullable=False)
    emp_home_ph = Column(String, nullable=False)
    emp_1st_pager = Column(String, nullable=False)
    emp_2nd_pager = Column(String, nullable=False)
    emp_1st_sec_ph = Column(String, nullable=False)
    emp_2nd_sec_ph = Column(String, nullable=False)
    emp_dvtc_ph = Column(String, nullable=False)
    emp_voip_ph = Column(String, nullable=False)
    emp_room_nbr = Column(String, nullable=False)
    emp_hm_addr_1_4 = Column(String, nullable=False)
    emp_hm_city = Column(String, nullable=False)
    emp_hm_state = Column(String, nullable=False)
    emp_hm_zip = Column(String, nullable=False)
    emp_ed_hi_lvl = Column(String, nullable=False)
    emp_ed_hideg = Column(String, nullable=False)
    emp_ed_himajor = Column(String, nullable=False)
    emp_vet_pref = Column(String, nullable=False)
    emp_mil_service = Column(String, nullable=False)
    emp_mil_cat = Column(String, nullable=False)
    cor_name = Column(String, nullable=False)
    onsite_loc = Column(String, nullable=False)
    offsite_loc = Column(String, nullable=False)
    hrs_on_contract = Column(Integer, nullable=False)
    emp_loc_ncr = Column(String, nullable=False)
    emp_gender = Column(String, nullable=False)


class VkIndia(Base):
    __tablename__ = "vk_india"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    idx = Column(Integer)
    dia_person_key = Column(String)
    person_inst_id = Column(String)
    ssn = Column(String)
    clearance_inst_id = Column(String)
    type = Column(String)
    lastname = Column(String)
    firstname = Column(String)
    middlename = Column(String)
    suffix = Column(String)
    cityofbirth = Column(String)
    stateofbirth = Column(String)
    countryofbirth = Column(String)
    eligibilitystatus = Column(String)
    ineligibilityreason = Column(String)
    grantingagency = Column(String)
    clearancelevel = Column(String)
    interim = Column(String)
    hascover = Column(String)
    citizenship = Column(String)
    iscover = Column(String)
    true_person_inst_id = Column(String)
    dateofbirth = Column(DateTime)
    eligibiltydate = Column(DateTime)


class VkKiloFcReporting(Base):
    __tablename__ = "vk_kilo_fc_reporting"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    inst_id = Column(String, nullable=False)
    parent_inst_id = Column(String, nullable=False)
    creation_datetime = Column(String, nullable=False)
    modified_datetime = Column(String, nullable=False)
    firstname = Column(String, nullable=False)
    middlename = Column(String, nullable=False)
    lastname = Column(String, nullable=False)
    other_names = Column(String, nullable=False)
    fc_report_number = Column(String, nullable=False)
    fc_report_status = Column(Integer, nullable=False)
    relationship_description = Column(String, nullable=False)
    nature_of_relationship = Column(String, nullable=False)
    date_of_birth = Column(String, nullable=False)
    age = Column(Integer, nullable=False)
    gender = Column(String, nullable=False)
    pob_city = Column(String, nullable=False)
    pob_country = Column(String, nullable=False)
    current_residence = Column(String, nullable=False)
    email = Column(String, nullable=False)
    first_encounter_date = Column(String, nullable=False)
    first_encounter_location = Column(String, nullable=False)
    first_encounter_circumstances = Column(String, nullable=False)
    first_encounter_initiated_by = Column(String, nullable=False)
    type_of_contact = Column(String, nullable=False)
    last_personal_contact_date = Column(String, nullable=False)
    last_personal_contact_location = Column(String, nullable=False)
    last_telephone_written_contact_date = Column(String, nullable=False)
    last_internet_contact_date = Column(String, nullable=False)
    contact_frequency_telephone_text = Column(Integer, nullable=False)
    contact_frequency_telephone_text_per = Column(String, nullable=False)
    contact_frequency_written = Column(Integer, nullable=False)
    contact_frequency_written_per = Column(String, nullable=False)
    contact_frequency_email = Column(String, nullable=False)
    contact_frequency_email_per = Column(String, nullable=False)
    contact_frequency_internet = Column(Integer, nullable=False)
    contact_frequency_internet_per = Column(String, nullable=False)
    has_affiliations_foreign_intel_gov = Column(String, nullable=False)
    affiliations_foreign_intel_gov = Column(String, nullable=False)
    has_affiliations_criminal_subversive = Column(String, nullable=False)
    affiliations_criminal_subversive = Column(String, nullable=False)
    affiliations_criminal_subversive_classification = Column(String, nullable=False)
    result_in_unusual_circumstance = Column(String, nullable=False)
    unusual_circumstance = Column(String, nullable=False)
    unusual_circumstance_classification = Column(String, nullable=False)
    additional_biographical_information_yes_no = Column(String, nullable=False)
    additional_biographical_information_classification = Column(String, nullable=False)
    further_discuss_reporting_yes_no = Column(String, nullable=False)
    further_discuss_reporting = Column(String, nullable=False)
    further_discuss_reporting_classification = Column(String, nullable=False)
    user_id = Column(Integer, nullable=False)
    modified_user_id = Column(Integer, nullable=False)
    nature_of_relationship_other = Column(String, nullable=False)
    contact_frequency_personal = Column(Integer, nullable=False)
    contact_frequency_personal_per = Column(String, nullable=False)
    affiliations_foreign_intel_gov_classification = Column(String, nullable=False)
    is_close_and_continuing_relationship = Column(String, nullable=False)
    close_and_continuing_relationship_description_classification = Column(
        String, nullable=False
    )
    subject_rm_person_version_inst_id = Column(String, nullable=False)
    submitter_rm_person_version_inst_id = Column(Integer, nullable=False)
    occupation = Column(String, nullable=False)
    job_position = Column(String, nullable=False)
    job_title = Column(String, nullable=False)
    employer_name = Column(String, nullable=False)
    employer_address = Column(String, nullable=False)
    dob_known = Column(String, nullable=False)
    idp = Column(String, nullable=False)
    fc_report_classification = Column(String, nullable=False)
    reported_datetime = Column(String, nullable=False)
    has_telephone_written_contact = Column(String, nullable=False)
    has_internet_contact = Column(String, nullable=False)
    phone_number_collection_id = Column(String, nullable=False)
    legacy_id = Column(Integer, nullable=False)
    citizenship_unknown = Column(Integer, nullable=False)
    last_personal_contact_date_unknown = Column(Integer, nullable=False)
    last_personal_contact_location_unknown = Column(Integer, nullable=False)
    last_personal_contact_circumstances_unknown = Column(Integer, nullable=False)
    last_telephone_written_contact_date_unknown = Column(Integer, nullable=False)
    last_telephone_written_contact_circumstances_unknown = Column(
        Integer, nullable=False
    )
    last_internet_contact_date_unknown = Column(Integer, nullable=False)
    last_internet_contact_circumstances_unknown = Column(Integer, nullable=False)
    has_personal_contact = Column(String, nullable=False)
    contact_citizenship = Column(String, nullable=False)
    contact_phone = Column(String, nullable=False)
    reporter_ssn = Column(String, nullable=False)
    dia_person_key = Column(String, nullable=False)


class VkKiloFtReporting(Base):
    __tablename__ = "vk_kilo_ft_reporting"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    inst_id = Column(String, nullable=False)
    traveller_rm_person_version_inst_id = Column(String, nullable=False)
    submitter_rm_person_version_inst_id = Column(String, nullable=False)
    supervisor_rm_person_container_inst_id = Column(String, nullable=False)
    idp_status = Column(Integer, nullable=False)
    ftrav_report_number = Column(String, nullable=False)
    trip_classification = Column(String, nullable=False)
    overall_classification = Column(String, nullable=False)
    idp_classification = Column(String, nullable=False)
    date_reported = Column(Integer, nullable=False)
    passport = Column(Integer, nullable=False)
    passport_type = Column(String, nullable=False)
    date_passport_expire = Column(Integer, nullable=False)
    date_last_at1 = Column(Integer, nullable=False)
    is_embassy_visit = Column(Integer, nullable=False)
    date_start_trip = Column(Integer, nullable=False)
    date_end_trip = Column(Integer, nullable=False)
    post_trip_report_reason = Column(String, nullable=False)
    signature = Column(String, nullable=False)
    emergency_contact_name = Column(String, nullable=False)
    emergency_contact_email = Column(String, nullable=False)
    is_embassy_within_us = Column(String, nullable=False)
    embassy_visited = Column(String, nullable=False)
    embassy_departure_mode_of_travel_id = Column(String, nullable=False)
    embassy_return_mode_of_travel_id = Column(String, nullable=False)
    embassy_departure_date = Column(String, nullable=False)
    embassy_return_date = Column(String, nullable=False)
    status = Column(String, nullable=False)
    date_supervisor_approved = Column(String, nullable=False)
    creation_datetime = Column(String, nullable=False)
    modified_datetime = Column(String, nullable=False)
    user_id = Column(Integer, nullable=False)
    modified_user_id = Column(Integer, nullable=False)
    legacy_traveling_alone = Column(String, nullable=False)
    legacy_date_last_defensive_travel = Column(String, nullable=False)
    ftrav_trip_review_inst_id = Column(String, nullable=False)
    draft_step = Column(Integer, nullable=False)
    travel_destination_rollup = Column(String, nullable=False)
    countries_rollup = Column(String, nullable=False)
    cities_rollup = Column(String, nullable=False)
    emergency_contact_phone_number_collection_id = Column(String, nullable=False)
    workflow_event_log_collection_id = Column(String, nullable=False)
    legacy_id = Column(String, nullable=False)
    reporter_ssn = Column(String, nullable=False)
    dia_person_key = Column(String, nullable=False)


class VkKiloOfficialTravel(Base):
    __tablename__ = "vk_kilo_official_travel"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    table_index = Column(String, nullable=False)
    organization = Column(String, nullable=False)
    dia_person_key = Column(String, nullable=False)
    emp_ssn = Column(String, nullable=False)
    emp_ssn_int = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    first_name = Column(String, nullable=False)
    tanum = Column(String, nullable=False)
    document_name = Column(String, nullable=False)
    document_type = Column(String, nullable=False)
    trip_type = Column(String, nullable=False)
    special_circumstances = Column(String, nullable=False)
    trip_purpose = Column(String, nullable=False)
    current_status = Column(String, nullable=False)
    date_of_current_status = Column(String, nullable=False)
    awaiting_status = Column(String, nullable=False)
    pnr_record_locator = Column(String, nullable=False)
    document_create_date = Column(String, nullable=False)
    signed_date = Column(String, nullable=False)
    last_ao_approved_date = Column(String, nullable=False)
    current_version_completed_date = Column(String, nullable=False)
    departure_date = Column(String, nullable=False)
    return_date = Column(String, nullable=False)
    total_days_tdy = Column(Integer, nullable=False)
    includes_spp = Column(String, nullable=False)
    cancelled_date = Column(String, nullable=False)
    actuals = Column(String, nullable=False)
    financial_reject = Column(String, nullable=False)
    advance_reject = Column(String, nullable=False)
    spp_reject = Column(String, nullable=False)
    destination_is_foreign = Column(String, nullable=False)
    destination_location = Column(String, nullable=False)
    destination_area = Column(String, nullable=False)
    trip_description = Column(String, nullable=False)
    traveler_email_address = Column(String, nullable=False)
    ao_email_address = Column(String, nullable=False)
    dta_id_email_address = Column(String, nullable=False)
    constructive_travel_flag = Column(String, nullable=False)
    multiple_loas = Column(String, nullable=False)
    loa_label = Column(String, nullable=False)
    loa_10_by_20 = Column(String, nullable=False)
    expenses_by_loa = Column(String, nullable=False)
    sdn = Column(String, nullable=False)
    reference = Column(String, nullable=False)
    foreign_travel_flag = Column(String, nullable=False)
    tentered_flag = Column(String, nullable=False)
    noncontract_fare_flag = Column(String, nullable=False)


class VkKiloTechsBorderCrossing(Base):
    __tablename__ = "vk_kilo_techs_border_crossing"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    table_index = Column(String, nullable=False)
    subject_unique_id = Column(String, nullable=False)
    subject = Column(String, nullable=False)
    tecs_record_id = Column(String, nullable=False)
    tecs_sur_name = Column(String, nullable=False)
    tecs_first_name = Column(String, nullable=False)
    tecs_middle_name = Column(String, nullable=False)
    tecs_date_of_birth = Column(String, nullable=False)
    document_nbr = Column(String, nullable=False)
    document_typ = Column(String, nullable=False)
    doc_country_cde = Column(String, nullable=False)
    inbound_outbound_ind = Column(String, nullable=False)
    location_cde = Column(String, nullable=False)
    port_of_entry = Column(String, nullable=False)
    crossing_dte = Column(String, nullable=False)
    crossing_time = Column(String, nullable=False)
    arrival_location = Column(String, nullable=False)
    departure_location = Column(String, nullable=False)
    arr_loc_compressed = Column(String, nullable=False)
    dep_loc_compressed = Column(String, nullable=False)
    itact_record_create_date = Column(String, nullable=False)


class VkMike(Base):
    __tablename__ = "vk_mike"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    table_index = Column(Integer, nullable=False)
    dia_person_key = Column(Integer, nullable=False)
    subjectssn = Column(String, nullable=False)
    subjectssn_int = Column(String, nullable=False)
    subjectname = Column(String, nullable=False)
    subjectdob = Column(String, nullable=False)
    agency = Column(String, nullable=False)
    directorate = Column(String, nullable=False)
    domain = Column(String, nullable=False)
    type = Column(String, nullable=False)
    sessionid = Column(String, nullable=False)
    sessiondate = Column(String, nullable=False)
    esopinion = Column(String, nullable=False)
    countermeasure = Column(String, nullable=False)
    primaryadmission = Column(String, nullable=False)
    otheradmissions = Column(String, nullable=False)
    referredto = Column(String, nullable=False)


class VkNovember(Base):
    __tablename__ = "vk_november"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    violation_id = Column(Integer, nullable=False)
    ssr_ln = Column(String, nullable=False)
    ssr_mn = Column(String, nullable=False)
    ssr_fn = Column(String, nullable=False)
    ssr_user_name = Column(String, nullable=False)
    ssr_phone = Column(String, nullable=False)
    ssr_email = Column(String, nullable=False)
    reportedby_parentid = Column(String, nullable=False)
    reportedby_ln = Column(String, nullable=False)
    reportedby_mn = Column(String, nullable=False)
    reportedby_fn = Column(String, nullable=False)
    reportedby_user_name = Column(String, nullable=False)
    reportedby_phone = Column(String, nullable=False)
    reportedby_email = Column(String, nullable=False)
    reportedby_office = Column(String, nullable=False)
    reportedby_directorate = Column(String, nullable=False)
    reportedby_work_location = Column(String, nullable=False)
    supervisor_name = Column(String, nullable=False)
    supervisor_phone = Column(String, nullable=False)
    supervisor_email = Column(String, nullable=False)
    cor = Column(String, nullable=False)
    cor_phone = Column(String, nullable=False)
    incident_location = Column(String, nullable=False)
    incident_involving = Column(String, nullable=False)
    date_incident = Column(String, nullable=False)
    date_report = Column(String, nullable=False)
    overall_classification = Column(String, nullable=False)
    details = Column(String, nullable=False)
    status_id = Column(Integer, nullable=False)
    creation_datetime = Column(String, nullable=False)
    user_id = Column(Integer, nullable=False)
    modified_datetime = Column(String, nullable=False)
    modified_user_id = Column(Integer, nullable=False)
    violation_number = Column(String, nullable=False)
    violation_idp_status = Column(Integer, nullable=False)
    incident_type = Column(String, nullable=False)
    incident_type_classification = Column(String, nullable=False)
    data_compromised = Column(String, nullable=False)
    cage_code = Column(String, nullable=False)
    contract_number = Column(String, nullable=False)
    contractor_name = Column(String, nullable=False)
    subject_parentid = Column(String, nullable=False)
    subject_inst_id = Column(Integer, nullable=False)
    subject_ln = Column(String, nullable=False)
    subject_mn = Column(String, nullable=False)
    subject_fn = Column(String, nullable=False)
    subject_user_name = Column(String, nullable=False)
    subject_phone = Column(String, nullable=False)
    subject_email = Column(String, nullable=False)
    subject_directorate = Column(String, nullable=False)
    subject_work_location = Column(String, nullable=False)
    violation_self_reported = Column(Integer, nullable=False)
    subject_office = Column(String, nullable=False)
    is_exportable = Column(Integer, nullable=False)


class VkXray(Base):
    __tablename__ = "vk_xray"
    __table_args__ = {"schema": "audit"}

    vuuid = Column(UUID, primary_key=True, server_default=text("uuid_generate_v4()"))
    ces_enrolee_id = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    first_name = Column(String, nullable=False)
    middle_name = Column(String, nullable=False)
    full_name = Column(String, nullable=False)
    ssn = Column(String, nullable=False)
    internal_org_id = Column(Integer, nullable=False)
    person_type = Column(String, nullable=False)
    current_address = Column(String, nullable=False)
    last_polygraph_date = Column(String, nullable=False)
    last_investigation_date = Column(String, nullable=False)
    last_investigation_type = Column(String, nullable=False)
    clearance_eligibility = Column(String, nullable=False)
    alert_id = Column(Integer, nullable=False)
    alert_source = Column(String, nullable=False)
    alert_severity = Column(String, nullable=False)
    alert_date = Column(String, nullable=False)
    alert_type = Column(String, nullable=False)
    alert_description = Column(String, nullable=False)
    matching_pii = Column(String, nullable=False)
    acknowledged_by = Column(String, nullable=False)
    acknowledged_date = Column(String, nullable=False)
    multiple_ce_enrollments = Column(String, nullable=False)
